---
- name: Set keyboard layouts
  shell: "setxkbmap us,ru"

- name: Make keyboard layouts persistent across restarts
  lineinfile:
    path: "/etc/default/keyboard"
    regexp: '^XKBLAYOUT=.*'
    line: 'XKBLAYOUT="us,ru"'
...
