---
- name: Ensure keyboard layouts are present
  shell: "setxkbmap -option grp:alt_shift_toggle us,ru"

- name: Make keyboard layout list persistent across restarts
  lineinfile:
    path: "/home/pi/.profile"
    create: true
    line: "setxkbmap -option grp:alt_shift_toggle us,ru"
...
